Repository octokit/plugin-paginate-graphql.js, pull requests merged in 2022-09, with the labels that each got.

#5 feat: initial version
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update-prettier.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  src/errors.ts
  src/extract-page-info.ts
  src/index.ts
  src/iterator.ts
  src/merge-responses.ts
  src/object-helpers.ts
  src/page-info.ts
  src/paginate.ts
  test/extract-page-infos.test.ts
  test/merge-responses.test.ts
  test/paginate-graphql.e2e.ts
  test/paginate.test.ts
  test/testHelpers/mock-octokit.ts
  test/testHelpers/mock-response.ts
  test/typescript-validate.ts
  tsconfig.json
Labels: feature

#8 fix: rename to `@octokit/plugin-paginate-graphql`
  package.json
Labels: bug

#9 docs(REAMDE): fix exported function name
  README.md
Labels: bug, documentation

#12 fix: Removes 'tbd.' statement from error-message
  src/errors.ts
Labels: maintenance

#13 test(e2e): Fixes e2e test import and adds iterator test
  test/paginate-graphql.e2e.ts
Labels: maintenance
