Repository octokit/plugin-paginate-graphql.js, pull requests merged in 2023-06, with the labels that each got.

#82 fix(build): switch to esbuild
  package-lock.json
  package.json
  scripts/build.mjs
  src/index.ts
  tsconfig.json
Labels: Type: Maintenance

#85 fix(build): bump tsconfig major version
  package-lock.json
  package.json
  src/errors.ts
  src/extract-page-info.ts
  test/tsconfig.test.json
Labels: Type: Maintenance

#78 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package.json
Labels: Type: Breaking change, Type: Maintenance

#89 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation

#88 feat: v3
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: Type: Breaking change, Type: Feature
