Repository octokit/plugin-paginate-graphql.js, pull requests merged in 2024-03, with the labels that each got.

#167 Spelling
  CONTRIBUTING.md
  README.md
  src/index.ts
  test/paginate-graphql.e2e.ts
  test/paginate.test.ts
  test/testHelpers/mock-octokit.ts
  test/typescript-validate.ts
Labels: Type: Breaking change, Type: Maintenance

#174 fix: use type imports for `@octokit/core`
  src/index.ts
  src/iterator.ts
  src/paginate.ts
Labels: Type: Bug

#175 feat: v5
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  scripts/build.mjs
  src/errors.ts
  src/extract-page-info.ts
  src/index.ts
  src/iterator.ts
  src/merge-responses.ts
  src/object-helpers.ts
  src/paginate.ts
  test/extract-page-infos.test.ts
  test/merge-responses.test.ts
  test/paginate-graphql.e2e.ts
  test/paginate.test.ts
  test/testHelpers/mock-octokit.ts
  test/testHelpers/mock-response.ts
  test/tsconfig.test.json
  test/typescript-validate.ts
Labels: Type: Breaking change, Type: Feature

#178 fix: actually output only ESM
  package.json
  scripts/build.mjs
  test/smoke.test.js
Labels: Type: Bug

#181 feat: export `VERSION`
  src/index.ts
  src/version.ts
  test/smoke.test.js
Labels: Type: Feature
